name: Run pytest
on: [pull_request]

jobs:
    pytest:
        name: pytest
        runs-on: ubuntu-latest
        steps:
        - name: GitHub Action for pytest
          uses: cclauss/GitHub-Action-for-pytest@0.5.0
