name: Run pytest
on: [pull_request]

jobs:
    pytest:
        name: pytest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run pytest
              uses: cclauss/GitHub-Action-for-pytest@0.5.0
              with:
                args: pytest
